name: Azure Storage Upload

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Upload to Azure Storage
        run: |
          account_name=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}
          account_key=${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}
          container_name=plugins
          source_directory=./plugins

          # Define the blob name (adjust as needed)
          blob_name=myblob

          # Check if the blob exists
          blob_exists=$(az storage blob exists --account-name $account_name --account-key $account_key --container-name $container_name --name $blob_name --output json | jq -r '.exists')

          # Delete the blob if it exists
          if [ "$blob_exists" == "true" ]; then
            az storage blob delete --account-name $account_name --account-key $account_key --container-name $container_name --name $blob_name --yes
          fi

          # Upload the new blob
          az storage blob upload-batch --account-name $account_name --account-key $account_key --destination $container_name --source $source_directory --pattern '*' --type block

